# Generated by Django 5.1.3 on 2024-11-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aslapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("video_file", models.FileField(upload_to="videos/")),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="streaks",
            field=models.IntegerField(default=0),
        ),
    ]
